import {
    Button,
    Switch,
    ComboBox,
    SpinBox,
    ScrollView,
    HorizontalBox,
} from "std-widgets.slint";

import { EffectElement } from "components/effect.slint";
import { EffectStruct } from "structs/effect_struct.slint";
import { Header } from "header.slint";
import { ImageDescription } from "components/image_description.slint";
import { EffectEnum } from "structs/effect_enum.slint";
import { AddEffect } from "components/add_effect.slint";
import { MoveDirection } from "structs/move_direction.slint";
import { MainImage } from "components/main_image.slint";

export component App inherits Window {
    maximized: true;
    title: "glipho";
    preferred-width: 1280px;
    preferred-height: 720px;

    // in properties
    in property <[EffectStruct]> effects;
    in property <image> original_image;
    in property <image> working_image;
    in property <bool> has_image: false;

    // loading
    in property <bool> is_loading;

    // callbacks
    callback effect_changed(id: int, value: int);
    callback effect_added(name: string, value: int);
    callback effect_removed(id: int);
    callback effect_moved(id: int, direction: MoveDirection);
    callback open_image();

    // TODO: separate this into component
    // adding effect
    private property <EffectEnum> new_effect_enum;
    private property <string> new_effect_name;
    private property <int> new_effect_value;

    VerticalLayout {
        // menu bar at the top of the screen
        Header { }

        // main content
        HorizontalLayout {
            spacing: 16px;
            padding: 16px;

            // effects
            ScrollView {
                width: 50%;

                VerticalLayout {
                    spacing: 12px;

                    // title
                    Text {
                        text: "Effects";
                        font-size: 16px;
                        font-weight: FontWeight.semi-bold;
                    }

                    // effects
                    VerticalLayout {
                        spacing: 8px;
                        for effect in effects: EffectElement {
                            effect: effect;
                            effect_changed(id, value) => {
                                root.effect_changed(id, value);
                            }
                            effect_removed(id) => {
                                root.effect_removed(id);
                            }
                            effect_moved(id, direction) => {
                                root.effect_moved(id, direction);
                            }
                        }
                    }

                    if effects.length == 0: Text {
                        text: "Start by adding your first effect...";
                        font-italic: true;
                    }

                    // add effect
                    AddEffect {
                        effect_added(name, value) => {
                            root.effect_added(name, value);
                        }
                    }

                    // filling at the bottom
                    Rectangle { }
                }
            }

            // images
            VerticalLayout {
                width: 50%;
                spacing: 12px;

                // title at the top of the screen
                Text {
                    text: "Image";
                    font-size: 16px;
                    font-weight: FontWeight.semi-bold;
                }

                // original image
                MainImage {
                    source: root.original_image;
                    has_image: root.has_image;
                    clickable: true;
                    vertical-stretch: 1;

                    clicked => { root.open_image() }
                }

                // icon: all done
                if !root.is_loading: Image {
                    colorize: whitesmoke;
                    height: 24px;
                    source: @image-url("assets/chevrons-down.svg");
                }

                // // icon: loading
                if root.is_loading: Image {
                    colorize: whitesmoke;
                    height: 24px;
                    source: @image-url("assets/refresh-cw.svg");

                    transform-rotation: 0deg;

                    animate transform-rotation {
                        duration: 1500ms;
                        iteration-count: -1;
                    }

                    init => {
                        self.transform-rotation = 360deg;
                    }
                }

                // working image
                MainImage {
                    source: root.working_image;
                    has_image: root.has_image;
                    clickable: false;
                    vertical-stretch: 1;
                }

                // filling at the bottom
                Rectangle { }
            }
        }
    }
}
