[[steps]]

[steps.Layer]
Brightness = 50

[[steps]]

[steps.Layer]
WrapBrightness = 50

[[steps]]
Save = "result.jpg"

[[steps]]
Layer = "ReverseBits"

[[steps]]
Save = "result2.jpg"

[[steps]]

[steps.Layer]
WrapBrightness = -100

[[steps]]
Layer = "Invert"

[[steps]]
Save = "result3.jpg"
